{{- if .Values.ebsCsiDriver.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "kubeadm-cluster-setup.fullname" . }}-ebs-install
  namespace: {{ .Release.Namespace }}
  annotations:
    "helm.sh/hook": post-install,post-upgrade
    "helm.sh/hook-weight": "1"
data:
  install.sh: |
    #!/bin/bash
    kubectl apply -k "github.com/kubernetes-sigs/aws-ebs-csi-driver/deploy/kubernetes/overlays/stable/?ref={{ .Values.ebsCsiDriver.version }}"
---
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "kubeadm-cluster-setup.fullname" . }}-ebs-installer
  namespace: {{ .Release.Namespace }}
  annotations:
    "helm.sh/hook": post-install,post-upgrade
    "helm.sh/hook-weight": "2"
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded
spec:
  template:
    spec:
      serviceAccountName: {{ include "kubeadm-cluster-setup.fullname" . }}-installer
      containers:
      - name: installer
        image: bitnami/kubectl:latest
        command: ["/bin/bash"]
        args: ["/scripts/install.sh"]
        volumeMounts:
        - name: script
          mountPath: /scripts
      volumes:
      - name: script
        configMap:
          name: {{ include "kubeadm-cluster-setup.fullname" . }}-ebs-install
          defaultMode: 0755
      restartPolicy: OnFailure
{{- end }}
