apiVersion: external-secrets.io/v1
kind: SecretStore
metadata:
  name: aws-secret-store
  namespace: {{ .Values.argocd.application.destinationNamespace }}
spec:
  provider:
    aws:
      service: SecretsManager
      region: ap-northeast-2
      auth: {}