{{- if .Values.ebsCsiDriver.enabled }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "kubeadm-cluster-setup.fullname" . }}-installer
  namespace: {{ .Release.Namespace }}
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "0"
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "kubeadm-cluster-setup.fullname" . }}-installer
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "0"
rules:
- apiGroups: ["*"]
  resources: ["*"]
  verbs: ["*"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "kubeadm-cluster-setup.fullname" . }}-installer
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "0"
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "kubeadm-cluster-setup.fullname" . }}-installer
subjects:
- kind: ServiceAccount
  name: {{ include "kubeadm-cluster-setup.fullname" . }}-installer
  namespace: {{ .Release.Namespace }}
{{- end }}
